name=T4_WIFI_CYW4343W
version=0.1.0
license=MIT
author=Warren Watson, Bill Greiman <fat16lib@sbcglobal.net>, Kurt Eckhardt, Warren Watson, Ian Wall
maintainer=Warren Watson 
sentence=Library for testing the Murata 1DX / CYW4343W WiFi chip on uSDHC1 and uSDHC2 on a Teensy 4.1 and custom Teensy boards. SdFat used as starting point
paragraph=
category=other
url=
repository=
architectures=*
